[env]
# supports arbitrary env vars so mise can be used like direnv/dotenv
PROJECT_NAME = "{{ config_root | basename }}"
# add the node_modules/.bin to the path
_.path = ['{{config_root}}/node_modules/.bin']

[tools]
node = "22"
yarn = "4.12.0"

[tasks.setup]
description = "Setup the project"
run = ['yarn install']

[tasks.build]
description = "Build the project"
run = 'gulp build'

[tasks.clean]
description = "Build the project"
run = ['gulp clean']
